config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'notifications_controller/index'
  get 'activities/index'
  get 'users/follow'
  get 'users/unfollow'
  get 'users_controller/follow'
  get 'users_controller/unfollow'
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'
  resources :profiles, only: [:show, :index] do
    collection do
      get :autocomplete
      get :settings
    end
  end
  resources :lists do
    resources :comments, module: :lists
    member do
      put "like" => "lists#vote"
    end
  end
  resources :users do
    member do
      get :follow
      get :unfollow
      get :follow_suggestions
      put "settings" => "users#settings"
    end
  end
  resources :activities
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
  acts_as_votable
  include ::PublicActivity::Common
  belongs_to :user
  has_many :items, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  accepts_nested_attributes_for :items, allow_destroy: true
  after_create :track_list_create
  after_update :track_list_update

  def notification_to_s
    "your list"
  end
end


def track_list_create
  $tracker.track( user_id, 'Created List')
end

def track_list_update
  $tracker.track( user_id, 'Updated List')
end

app/controllers/lists/comments_controller.rb
class Lists::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = List.find(params[:list_id])
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :set_list, only: [:show, :edit, :update, :destroy, :vote]
  respond_to :js, :json, :html
  def show
    @people_who_liked = @list.votes_for.up.by_type(User).voters
  end

  def index
  end

  def new
    @list = List.new items: [Item.new]
  end


  def edit
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      @list.create_activity :create, owner: current_user
      redirect_to list_path(@list), notice: 'List was successfully created'
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      @list.create_activity :update, owner: current_user
      redirect_to list_path(@list), notice: 'List was successfully created'
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to profile_path(current_user), notice: 'List was successfully deleted.'
  end

  def vote
    if !current_user.liked? @list
      @list.liked_by current_user
      #create like notification for the user
      Notification.create(recipient: @list.user, actor: current_user, action: "liked", notifiable: @list)
      $tracker.track( user_id , "Liked a List")
    elsif current_user.liked? @list
      @list.unliked_by current_user
    end
  end


  private

  def set_list
    @list = List.find(params[:id])
  end


  def list_params
    params.require(:list).permit(:name, items_attributes: Item.attribute_names.map(&:to_sym).push(:_destroy))
  end
end

app/views/lists/_form.html.erb
<div class="form-list">
  <%= simple_form_for (@list), html: { autocomplete: 'off' } do |f|  %>
    <%= f.error_notification  %>
    <div class= 'form-inputs'>
    <h3>  <%= f.input :name, :placeholder => 'Give your list a name'  %></h3>
    </div>
    <h3>Items</h3>
    <table class= 'table'>
      <tbody class='items'>
        <%= f.simple_fields_for :items do |builder| %>
        <%= render 'item_fields', f: builder %>
        <%end %>
      </tbody>
    </table>
    <div class= 'form-actions'>
      <%= link_to_add_association 'Add Item', f, :items, class: 'btn btn-primary btn-list', data: {association_insertion_node: '.items', association_insertion_method: :append } %>
    <%= f.button :submit, "Save List", class: 'btn btn-primary btn-list' %>
    </div>
  <% end %>
</div>

app/views/lists/_item_fields.html.erb
<tr class= "nested-fields">
  <td>
      <%= link_to_remove_association "", f, class: "fas fa-trash-alt" %>
      <a href="#"> <i class="fas fa-camera"></i></a>
  </td>

  <td class="input-fields"> <%= f.input :name, label: false, :placeholder => 'Name or URL' %></td>
  <td class="input-fields photo-input" style="display:none;"><%= f.input :photo, label: false%></td>
  <td class="input-fields"><%= f.input :photo_cache, as: :hidden %></td>
  <td class="input-fields"> <%= f.input :description, label: false, :input_html => {:rows => 5}, :placeholder => 'Description...' %></td>
</tr>

app/views/lists/_normal_item.html.erb
<div class="counter"> <%= counter %> </div>
  <div class="normal-card-body">
    <h5 class="normal-card-title"><%= item.name %></h5>
    <% if item.photo.url != nil %>
      <div class="user-image-container">
      <%= image_tag((item.photo.url), class: "user-image") %>
      </div>
    <% end %>
    <p class="item-description"><%= item.description %></p>
  </div>
  <div class="normal-card-bottom-border"> </div>

app/views/lists/_url_item.html.erb
<% output = item.preview %>
<%= link_to output[3], class: "url-link", target: :_blank do   %>
  <div class="counter"> <%= counter %> </div>
    <div class="url-card-body">
      <div class ="url-card-image-container">
        <%= image_tag((output[0]), class: "url-image") %>
      </div>
      <div class="url-card-text">
        <h5 class="url-card-title"><%= output[2] %></h5>
        <p class="url-card-description"> <%= output[1] %></p>
        <p class="url-card-url-root"> <%= output[4] %> </p>
      </div>
    </div>
  <p class= "item-description"><%= item.description %></p>
<% end %>

app/views/lists/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-6">
      <h1>Editing List</h1>
      <%= render 'form', list: @list %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-6">
      <h1>New List</h1>
      <%= render 'form', list: @list %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-6">
      <div class="card">
        <div class="card-header"><h2><%= @list.name %><h2></div>
          <% counter = 0 %>
          <% @list.items.each do |item| %>
            <% counter = counter + 1 %>
            <% if item.url != nil %>
              <%= render "url_item", item: item, counter: counter %>
            <%else%>
              <%= render "normal_item", item: item, counter: counter %>
            <% end %>
          <% end %>
          <div class="like">
            <%= link_to like_list_path(@list), :class => "like-btn", method: :put, remote: :true do %>
            <%= liked_list(@list) %>
            <% end %>
            <%= link_to "", "data-toggle" => "modal", "data-target" => "#likeModalLong" do %>
            <span class="likes-count"><%= @list.get_upvotes.size %></span>
            <% end %>
          </div>
          <div class="item-footer">
            <% if @list.user == current_user %>
            <div class="item-footer-left">
              <%= link_to list_path(@list), method: :delete do %>
              <i class="fas fa-trash-alt"></i>
              <% end %>
              <%= link_to edit_list_path(@list) do %>
              <i class="fas fa-pencil-alt"></i>
              <% end %>
            </div>
            <% end %>
            <div class="item-footer-right">
              <%= social_share_button_tag(@list.name, :url => list_path(@list)) %>
            </div>
          </div>
        </div>
        <h3>Comments</h3>
        <div class="comments" id="comments">
          <%= render partial: "comments/form", locals: {commentable: @list} %>
          <%= render @list.comments.where(parent_id: nil), max_nesting: 3 %>
        </div>
        <div class="modal fade" id="likeModalLong" tabindex="-1" role="dialog" aria-labelledby="likeModalLongTitle" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="likeModalLongTitle">People who Liked</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <ul class="user-lists">
                  <% @people_who_liked.each do |liker| %>
                  <%= render 'profiles/user_card', user: liker %>
                  <% end %>
                </ul>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
   </div>
</div>

app/views/lists/vote.js.erb
<% if current_user.liked? @list %>
  $('.fa-heart').addClass('liked');
  <% else %>
  $('.fa-heart').removeClass('liked');
<% end %>
$('.likes-count').html("<%= @list.get_upvotes.size %>")