config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'notifications_controller/index'
  get 'activities/index'
  get 'users/follow'
  get 'users/unfollow'
  get 'users_controller/follow'
  get 'users_controller/unfollow'
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'
  resources :profiles, only: [:show, :index] do
    collection do
      get :autocomplete
      get :settings
    end
  end
  resources :lists do
    resources :comments, module: :lists
    member do
      put "like" => "lists#vote"
    end
  end
  resources :users do
    member do
      get :follow
      get :unfollow
      get :follow_suggestions
      put "settings" => "users#settings"
    end
  end
  resources :activities
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index, :autocomplete]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json, :js
  impressionist :actions=>[:show]

  def index
    search = params[:term].present? ? params[:term] : nil
    @users = if search
    User.search(search)
    else
      User.all
    end
  end

  def autocomplete
    render json: User.search(params[:query], {
      fields: ["first_name", "last_name", "username"],
      match: :word_start,
      limit: 10,
      load: false,
      misspellings: false
    }).map(&:username)
  end


  def show
    impressionist(@user)
    @followers = @user.followers
    @following = @user.all_following
  end



  private
  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :photo, :photo_cache)
  end
end

app/views/profiles/_follow.html.erb
<%= link_to "Follow", follow_user_path(@user), class: "btn btn-primary follow"%>

app/views/profiles/_follow_form.html.erb
<% unless current_user==@user %>
  <div id="follow_form">
  <% if current_user.is_a?(User) && current_user.following?(@user) %>
    <%= render 'profiles/unfollow' %>
  <% else %>
    <%= render 'profiles/follow' %>
  <% end %>
  </div>
<% end %>

app/views/profiles/_glimpse_list_card.html.erb
<div class="col-sm-5">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= list.name %></h5>
      <div class="item-preview">
        <% if list.items.first.url != nil %>
            <%= render "glimpse_url_item", item: list.items.first %>
          <%else%>
            <%= render 'glimpse_normal_item', item: list.items.first
            %>
          <% end %>
      </div>
        <div class="controls">
          <div class="controls-left">
            <%=link_to "Explore", list_path(list),  class: 'btn btn-primary' %>
          </div>
          <div class="controls-right">
             <%= liked_list(list) %>
            <span class="likes-count"><%= list.get_upvotes.size %></span>
            </ul>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/profiles/_glimpse_normal_item.html.erb
<div class="counter">1</div>
  <div class="glimpse-normal-card-body">
    <% if item.photo.url != nil %>
      <div class="glimpse-user-image-container">
      <%= image_tag((item.photo.url), class: "user-image") %>
      </div>
    <% end %>
    <div class="glimpse-card-text">
      <h5 class="normal-card-title"><%= item.name %></h5>
      <p class="item-description"><%= item.description %></p>
    </div>
  </div>

app/views/profiles/_glimpse_url_item.html.erb
<% output = item.preview %>
<%= link_to output[3], class: "url-link", target: :_blank do   %>
  <div class="counter">1</div>
    <div class="glimpse-url-card-body">
      <div class ="url-card-image-container">
        <%= image_tag((output[0]), class: "url-image") %>
      </div>
      <div class="url-card-text">
        <h5 class="glimpse-url-card-title"><%= output[2] %></h5>
        <p class="glimpse-url-card-description"> <%= output[1] %></p>
        <p class="glimpse-url-card-url-root"> <%= output[4] %> </p>
      </div>
    </div>
  <p class= "item-description"><%= item.description %></p>
<% end %>

app/views/profiles/_profile_container.html.erb
<aside class="col-md-3 col-4 left-column">
    <section>
      <div class="small-profile-header-wrapper">
        <div class="container small-profile-header-container user-text-center">
          <div class="small-profile-header-infos">
            <%= cl_image_tag current_user.photo, width: 150, height: 150, crop: :thumb, gravity: :face, secure: true, class: "avatar-bordered"%>
            <h1><%= current_user.username %></h1>
            <h2><%= current_user.description%></h2>
          </div>
          <div class="small-tabs">
            <a class="tab small active" href="#">
              <% total = 0 %>
              <% current_user.lists.each do |list| %>
                <% total += list.get_upvotes.size %>
              <%end %>
              <h3><%=total%></h3>
              <p>Likes</p>
            </a>
            <a class="tab small" href="#">
              <h3><%= current_user.lists.count %></h3>
              <p>Lists</p>
            </a>
            <a class="tab small" href="#">
              <h3><%= current_user.followers_count %></h3>
              <p>Followers</p>
            </a>
            <a class="tab small" href="#">
              <h3><%= current_user.follow_count %></h3>
              <p>Following</p>
            </a>
          </div>
        </div>
        <div class="profile-views">
          <h2><%= current_user.impressionist_count %></h2>
          <h3>Profile Views</h3>
        </div>
      </div>
    </section>
  </aside>

app/views/profiles/_unfollow.html.erb
<%= link_to "Unfollow", unfollow_user_path(@user), class: "btn btn-primary follow"%>

app/views/profiles/_user_card.html.erb
<%= link_to profile_path(user) do %>
<li class="user">
  <div class="user-upper-part">
    <%= cl_image_tag user.photo, width: 150, height: 150, crop: :thumb, gravity: :face, secure: true, class: "avatar-large"%>
    <div class="user-name">
      <h3><%= "@" + user.username %><h3>
        <p><%= [user.first_name, user.last_name].join(" ")%></p>
        <% @user = user  %>
      </div>
    </div>
    <%= render '/profiles/follow_form' %>
    <div class="user-footer">
      <div class="user-stat">
        <p><%= user.lists.count %></p>
        <p class="user-text">Lists</p>
      </div>
      <div class="user-stat">
        <p><%= user.followers_count %></p>
        <p class="user-text">Followers</p>
      </div>
      <div class="user-stat">
        <p><%= user.follow_count %></p>
        <p class="user-text">Following</p>
      </div>
    </div>
  </li>
<% end %>

app/views/profiles/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-6">
      <ul class="user-lists">
        <% @users.each do |user| %>
          <%= render 'user_card', user: user %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="profile-header-wrapper">
      <div class="container profile-header-container text-center">
        <div class="profile-header-infos">
          <%= cl_image_tag @user.photo, width: 150, height: 150, crop: :thumb, gravity: :face, secure: true, class: "avatar"%>
          <h1><%= @user.username %></h1>
          <h2><%= @user.description%></h2>
          <%= render 'follow_form' %>
        </div>
        <div class="tabs">
          <a class="tab active" href="#">
            <% total = 0 %>
            <% @user.lists.each do |list| %>
              <% total += list.get_upvotes.size %>
            <%end %>
            <h3><%=total%></h3>
            <p>Likes</p>
          </a>
          <a class="tab" href="">
            <h3><%= @user.lists.count %></h3>
            <p>Lists</p>
          </a>
          <%= link_to "", :class => "tab", "data-toggle" => "modal", "data-target" => "#followerModalLong" do%>
            <h3><%= @user.followers_count %></h3>
            <p>Followers</p>
            <% end %>
          <%= link_to "", :class => "tab", "data-toggle" => "modal", "data-target" => "#followingModalLong" do %>
            <h3><%= @user.follow_count %></h3>
            <p>Following</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row justify-content-center">
  <% @user.lists.each do |list| %>
  <%= render 'glimpse_list_card', list: list %>
  <%end %>
</div>


<!-- Modal -->
<div class="modal fade" id="followerModalLong" tabindex="-1" role="dialog" aria-labelledby="followerModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="followerModalLongTitle">Followers</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="user-lists">
            <% @followers.each do |follower| %>
                  <%= render 'user_card', user: follower %>
              <% end %>
          </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="followingModalLong" tabindex="-1" role="dialog" aria-labelledby="followingModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="followingModalLongTitle">Followers</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="user-lists">
            <% @following.each do |following| %>
                <%= render 'user_card', user: following %>
              <% end %>
          </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>