config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'notifications_controller/index'
  get 'activities/index'
  get 'users/follow'
  get 'users/unfollow'
  get 'users_controller/follow'
  get 'users_controller/unfollow'
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'
  resources :profiles, only: [:show, :index] do
    collection do
      get :autocomplete
      get :settings
    end
  end
  resources :lists do
    resources :comments, module: :lists
    member do
      put "like" => "lists#vote"
    end
  end
  resources :users do
    member do
      get :follow
      get :unfollow
      get :follow_suggestions
      put "settings" => "users#settings"
    end
  end
  resources :activities
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="sticky-top navbar-listy">
  <div class="navbar-left">
      <%= link_to activities_path, class: "navbar-listy-brand" do %>
      <i class="fas fa-th-list logo"></i>
      <% end %>
      <div class="vl"></div>
      <h1 class="logo-listy">Listy</h1>
  </div>

    <!-- Right Navigation -->
  <div class="navbar-listy-right hidden-xs hidden-sm">
    <div class="navbar-search">
      <i class="fas fa-search"></i>
      <%= form_tag(profiles_path, method: :get, class: "form-inline", role: 'search') do %>
        <div class="input-group-search">
          <%= text_field_tag :term,
            params[:term],
            id: 'users_search',
            autocomplete: :off,
            placeholder: 'User?',
            class: 'form-control' %>
        </div>
      <% end %>
    </div>
    <% if current_user.is_a?(User) %>
    <div class="icon">
      <div class="btn-group dropleft" data-behavior="notifications">
        <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#" data-behavior="notifications-link">
          <i class="far fa-bell icon-selector"></i><span class="num" data-behavior="unread-count"></span>
                <p>Notifications</p>
            </a>
          <div class="dropdown-menu dropdown-menu-right navbar-listy-notifications-dropdown" data-behavior="notification-items">
            <!-- thats where the notifcations appear -->
          </div>
      </div>
    </div>
    <%= link_to activities_path, :class => "icon icon-hidden-mobile" do %>
      <i class="fas fa-home icon-selector"></i>
      <p>Home</p>
    <% end %>
    <%= link_to new_list_path, :class => "icon icon-hidden-mobile" do %>
      <i class="fas fa-edit icon-selector"></i>
      <p>New List</p>
    <% end %>
    <div class="navbar-listy-item">
      <div class="dropdown">
        <%= cl_image_tag current_user.photo, width: 150, height: 150, crop: :thumb, gravity: :face, secure: true, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-listy-dropdown-menu">
            <li>
              <%= link_to profile_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path(current_user) do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
            </ul>
          </div>
        </div>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Sign Up"), new_user_registration_path, class: "btn btn-info btn-user" %>
        <%= link_to t(".sign_in", default: "Log In"), new_user_session_path, class: "btn btn-primary btn-user" %>
      <% end %>
    </div>
</nav>